Add client graphql mutation to store data on server
karsil/MobileReceptionAtlas pull request #16
Opened 2019-02-11 14:24 UTC by nilsjung

## for testing
you have to edit the current address in `frontend/client/index.js` to the ip of your local machine. 
also make sure, that the _mongodb_ and _server_ are running and listening on the right port and address.

2019-02-11 15:52 UTC, karsil requested changes

2019-02-11 15:52 UTC, karsil commented on frontend/reducers/index.js
> +        data: addElementToArray(elements, state.data),
Warning `[Unhandled promise rejection: TypeError: Invalid attempt to spread non-iterable instance]`

2019-02-11 15:52 UTC, karsil commented on frontend/reducers/index.js
> +    let elements = [...array];
Warning, see above

2019-02-13 14:07 UTC, nilsjung commented
* I fixed the warnings and errors. This was a problem regarding the return value of the `Array.push()` function. This returns the new array length and not the new created array.
* I fixed the different graphql results that were stored local in the data-array. now they are consistent and can be stored safely with `store.data.push`
* I merge the actual master

2019-02-18 10:50 UTC, karsil submitted a review, later dismissed

2019-02-18 10:57 UTC, karsil approved these changes
Approved with disclaimer to correspondig bug ticket (issue #22)

2019-02-18 10:57 UTC, merged