Refactor Graphql Query Structure
karsil/MobileReceptionAtlas pull request #61
Opened 2019-03-09 18:24 UTC by nilsjung

2019-03-09 21:01 UTC, karsil requested changes

2019-03-09 21:01 UTC, karsil commented on backend/graphql/databaseQuery.js
> +    if (radius !== 0) {
Check for larger 0.

2019-03-09 21:01 UTC, karsil commented on frontend/components/ButtonField/ButtonField.js
> +                            this.props.getConnectionDataAction(50000)
Might declare radius variable more prominent.

2019-03-09 21:01 UTC, karsil commented on frontend/components/Root/Root.Action.js
> +            .catch(() => isSearchingForLocation(false));
dispatch?

2019-03-09 21:01 UTC, karsil commented on frontend/graphql/mutation.js
> +        refetchQueries: [{ query: getAllConnectionData }],
**Throws error**: `You must wrap the query string in a "gql" tag`.
Has been checked by logging `createConnectionData`

2019-03-09 21:11 UTC, karsil commented
Very good call for this merge request. Much easier for future implementations!

2019-03-10 10:02 UTC, nilsjung commented on backend/graphql/databaseQuery.js
> +    if (radius !== 0) {
good point

2019-03-10 10:04 UTC, nilsjung commented on frontend/components/Root/Root.Action.js
> +            .catch(() => isSearchingForLocation(false));
i will change this, although the error seems to be a bit older :grimacing:

2019-03-10 10:04 UTC, nilsjung commented on frontend/graphql/mutation.js
> +        refetchQueries: [{ query: getAllConnectionData }],
i will take a look at this.

2019-03-10 12:57 UTC, karsil approved these changes
Looks nice and is running!

2019-03-10 13:01 UTC, merged